insert into Products (name, stock) values ('Bacardi Breezer - Tropical', 2596);
insert into Products (name, stock) values ('Corn Meal', 8372);
insert into Products (name, stock) values ('Nut - Macadamia', 538);
insert into Products (name, stock) values ('Pepper - Red Thai', 3192);
insert into Products (name, stock) values ('Rabbit - Whole', 2300);
insert into Products (name, stock) values ('Extract - Raspberry', 2357);
insert into Products (name, stock) values ('Cookies - Englishbay Wht', 4910);
insert into Products (name, stock) values ('Beef - Ground Lean Fresh', 9120);
insert into Products (name, stock) values ('Cup - Paper 10oz 92959', 2);
insert into Products (name, stock) values ('Wine - Red, Black Opal Shiraz', 4947);
insert into Products (name, stock) values ('Lettuce - Spring Mix', 7591);
insert into Products (name, stock) values ('Beer - True North Lager', 2059);
insert into Products (name, stock) values ('Pants Custom Dry Clean', 9851);
insert into Products (name, stock) values ('Flour - Semolina', 9238);
insert into Products (name, stock) values ('Soap - Hand Soap', 5633);
insert into Products (name, stock) values ('Flower - Commercial Bronze', 2525);
insert into Products (name, stock) values ('Cookie Trail Mix', 2891);
insert into Products (name, stock) values ('Cheese - St. Andre', 6633);
insert into Products (name, stock) values ('Mustard - Dry, Powder', 2766);
insert into Products (name, stock) values ('Thyme - Dried', 114);
insert into Products (name, stock) values ('Red Currant Jelly', 4338);
insert into Products (name, stock) values ('Pickerel - Fillets', 629);
insert into Products (name, stock) values ('Island Oasis - Sweet And Sour Mix', 2466);
insert into Products (name, stock) values ('Bagel - Sesame Seed Presliced', 1018);
insert into Products (name, stock) values ('Cake - Night And Day Choclate', 9830);
insert into Products (name, stock) values ('Cheese - St. Paulin', 6549);
insert into Products (name, stock) values ('Flounder - Fresh', 2471);
insert into Products (name, stock) values ('Veal - Heart', 9275);
insert into Products (name, stock) values ('Compound - Raspberry', 409);
insert into Products (name, stock) values ('Tequila Rose Cream Liquor', 8472);
insert into Products (name, stock) values ('White Baguette', 7405);
insert into Products (name, stock) values ('Peas - Pigeon, Dry', 3132);
insert into Products (name, stock) values ('Lemonade - Natural, 591 Ml', 9309);
insert into Products (name, stock) values ('Potatoes - Idaho 80 Count', 9985);
insert into Products (name, stock) values ('Coffee - 10oz Cup 92961', 4272);
insert into Products (name, stock) values ('Wine - Sherry Dry Sack, William', 180);
insert into Products (name, stock) values ('Sauce - Fish 25 Ozf Bottle', 4240);
insert into Products (name, stock) values ('Chef Hat 25cm', 3142);
insert into Products (name, stock) values ('Turkey - Breast, Smoked', 3811);
insert into Products (name, stock) values ('Tomatoes - Vine Ripe, Yellow', 4464);
insert into Products (name, stock) values ('Green Scrubbie Pad H.duty', 5194);
insert into Products (name, stock) values ('Pepper - Black, Whole', 658);
insert into Products (name, stock) values ('Otomegusa Dashi Konbu', 7012);
insert into Products (name, stock) values ('Wine - Crozes Hermitage E.', 7365);
insert into Products (name, stock) values ('Cheese - Gouda', 419);
insert into Products (name, stock) values ('Mushroom - Chanterelle, Dry', 685);
insert into Products (name, stock) values ('Praline Paste', 9167);
insert into Products (name, stock) values ('Oven Mitts 17 Inch', 5423);
insert into Products (name, stock) values ('Bread - Multigrain', 6065);
insert into Products (name, stock) values ('Beef - Flank Steak', 5352);
insert into Products (name, stock) values ('Pastry - Cheese Baked Scones', 5516);
insert into Products (name, stock) values ('Squash - Guords', 9813);
insert into Products (name, stock) values ('Mudslide', 6921);
insert into Products (name, stock) values ('Cheese - Le Cheve Noir', 8603);
insert into Products (name, stock) values ('Pastry - Butterscotch Baked', 7041);
insert into Products (name, stock) values ('Appetizer - Smoked Salmon / Dill', 6864);
insert into Products (name, stock) values ('Rice Paper', 80);
insert into Products (name, stock) values ('Wine - Red, Cooking', 5109);
insert into Products (name, stock) values ('Pails With Lids', 5692);
insert into Products (name, stock) values ('Oxtail - Cut', 5852);
insert into Products (name, stock) values ('Wine - Chateau Aqueria Tavel', 2769);
insert into Products (name, stock) values ('Mangoes', 7907);
insert into Products (name, stock) values ('Stock - Beef, Brown', 6277);
insert into Products (name, stock) values ('Corn Meal', 6482);
insert into Products (name, stock) values ('Oil - Pumpkinseed', 9544);
insert into Products (name, stock) values ('Lotus Root', 8094);
insert into Products (name, stock) values ('Lobster - Tail 6 Oz', 5374);
insert into Products (name, stock) values ('The Pop Shoppe - Grape', 5700);
insert into Products (name, stock) values ('Juice - Apple, 1.36l', 5853);
insert into Products (name, stock) values ('Ostrich - Prime Cut', 7026);
insert into Products (name, stock) values ('Godiva White Chocolate', 4028);
insert into Products (name, stock) values ('Beef Ground Medium', 2531);
insert into Products (name, stock) values ('Cleaner - Comet', 1887);
insert into Products (name, stock) values ('Truffle Cups Green', 9867);
insert into Products (name, stock) values ('Oregano - Dry, Rubbed', 9449);
insert into Products (name, stock) values ('Sauce - Cranberry', 3456);
insert into Products (name, stock) values ('Pomello', 8619);
insert into Products (name, stock) values ('Cheese - Stilton', 8058);
insert into Products (name, stock) values ('Lettuce - Green Leaf', 6958);
insert into Products (name, stock) values ('The Pop Shoppe - Cream Soda', 3464);
insert into Products (name, stock) values ('Pork - Smoked Kassler', 1439);
insert into Products (name, stock) values ('Beans - Navy, Dry', 9219);
insert into Products (name, stock) values ('Muffin Chocolate Individual Wrap', 2206);
insert into Products (name, stock) values ('Coffee - Espresso', 6466);
insert into Products (name, stock) values ('Wine - Cotes Du Rhone Parallele', 1689);
insert into Products (name, stock) values ('Chef Hat 25cm', 7827);
insert into Products (name, stock) values ('Lid Coffee Cup 8oz Blk', 9486);
insert into Products (name, stock) values ('Veal - Knuckle', 1247);
insert into Products (name, stock) values ('Pancetta', 4693);
insert into Products (name, stock) values ('Meldea Green Tea Liquor', 6569);
insert into Products (name, stock) values ('Pastrami', 6061);
insert into Products (name, stock) values ('Mint - Fresh', 708);
insert into Products (name, stock) values ('Wine - Cava Aria Estate Brut', 497);
insert into Products (name, stock) values ('Longos - Chicken Caeser Salad', 5362);
insert into Products (name, stock) values ('Chinese Foods - Chicken Wing', 5260);
insert into Products (name, stock) values ('Croissants Thaw And Serve', 4759);
insert into Products (name, stock) values ('Oyster - In Shell', 157);
insert into Products (name, stock) values ('Soup - Cream Of Potato / Leek', 9711);
insert into Products (name, stock) values ('Guava', 2998);
insert into Products (name, stock) values ('Wine - Ice Wine', 8336);
insert into Products (name, stock) values ('Oyster - In Shell', 4329);
insert into Products (name, stock) values ('Sping Loaded Cup Dispenser', 7205);
insert into Products (name, stock) values ('Tuna - Loin', 6627);
insert into Products (name, stock) values ('Rice - Brown', 1474);
insert into Products (name, stock) values ('Wine - Vouvray Cuvee Domaine', 3119);
insert into Products (name, stock) values ('Bag - Bread, White, Plain', 8181);
insert into Products (name, stock) values ('Bread - White, Unsliced', 7408);
insert into Products (name, stock) values ('Waffle Stix', 9089);
insert into Products (name, stock) values ('Bar - Sweet And Salty Chocolate', 2117);
insert into Products (name, stock) values ('Grenadillo', 2144);
insert into Products (name, stock) values ('Soup - Campbells, Minestrone', 9336);
insert into Products (name, stock) values ('Sun - Dried Tomatoes', 5438);
insert into Products (name, stock) values ('Chocolate - Dark', 6519);
insert into Products (name, stock) values ('Steel Wool', 4747);
insert into Products (name, stock) values ('Wheat - Soft Kernal Of Wheat', 915);
insert into Products (name, stock) values ('Mackerel Whole Fresh', 9115);
insert into Products (name, stock) values ('Miso Paste White', 7779);
insert into Products (name, stock) values ('Potatoes - Idaho 100 Count', 4455);
insert into Products (name, stock) values ('Ginsing - Fresh', 383);
insert into Products (name, stock) values ('Vinegar - Balsamic', 1980);
insert into Products (name, stock) values ('Tart Shells - Sweet, 3', 9701);
insert into Products (name, stock) values ('Horseradish Root', 3530);
insert into Products (name, stock) values ('Sour Puss Sour Apple', 9236);
insert into Products (name, stock) values ('Cheese - Ricotta', 9227);
insert into Products (name, stock) values ('Raspberries - Fresh', 8288);
insert into Products (name, stock) values ('Muffin Mix - Oatmeal', 7253);
insert into Products (name, stock) values ('Quail - Eggs, Fresh', 2135);
insert into Products (name, stock) values ('Cheese - Goat', 5938);
insert into Products (name, stock) values ('Lettuce - Lambs Mash', 2428);
insert into Products (name, stock) values ('Sausage - Chorizo', 6363);
insert into Products (name, stock) values ('Cheese - Boursin, Garlic / Herbs', 6410);
insert into Products (name, stock) values ('Salmon Steak - Cohoe 8 Oz', 1890);
insert into Products (name, stock) values ('Shortbread - Cookie Crumbs', 9771);
insert into Products (name, stock) values ('Garlic - Elephant', 973);
insert into Products (name, stock) values ('Tea - Herbal I Love Lemon', 9592);
insert into Products (name, stock) values ('Olives - Kalamata', 7226);
insert into Products (name, stock) values ('Wine - White, Gewurtzraminer', 708);
insert into Products (name, stock) values ('Kohlrabi', 7161);
insert into Products (name, stock) values ('Thyme - Lemon, Fresh', 6634);
insert into Products (name, stock) values ('Nantucket Cranberry Juice', 302);
insert into Products (name, stock) values ('Otomegusa Dashi Konbu', 2244);
insert into Products (name, stock) values ('Couscous', 7334);
insert into Products (name, stock) values ('Tart Shells - Sweet, 4', 7609);
insert into Products (name, stock) values ('Monkfish - Fresh', 2442);
insert into Products (name, stock) values ('Chicken - Thigh, Bone In', 9876);
insert into Products (name, stock) values ('Fudge - Cream Fudge', 8772);
insert into Products (name, stock) values ('Appetizer - Mushroom Tart', 7103);
insert into Products (name, stock) values ('Cheese - Cheddar, Medium', 7987);
insert into Products (name, stock) values ('Chicken - Leg, Boneless', 307);
insert into Products (name, stock) values ('Wine - George Duboeuf Rose', 9781);
insert into Products (name, stock) values ('Ranchero - Primerba, Paste', 5526);
insert into Products (name, stock) values ('Orange - Blood', 4667);
insert into Products (name, stock) values ('Lettuce - Frisee', 4610);
insert into Products (name, stock) values ('Pasta - Fusili, Dry', 1745);
insert into Products (name, stock) values ('Arctic Char - Fresh, Whole', 9577);
insert into Products (name, stock) values ('Lamb - Pieces, Diced', 3695);
insert into Products (name, stock) values ('Veal - Osso Bucco', 3832);
insert into Products (name, stock) values ('Milk - 2%', 4195);
insert into Products (name, stock) values ('Lamb - Whole, Fresh', 1491);
insert into Products (name, stock) values ('Sprouts - Baby Pea Tendrils', 3037);
insert into Products (name, stock) values ('Crab - Claws, 26 - 30', 467);
insert into Products (name, stock) values ('Nectarines', 9164);
insert into Products (name, stock) values ('Beans - Butter Lrg Lima', 4814);
insert into Products (name, stock) values ('Tart Shells - Sweet, 3', 2962);
insert into Products (name, stock) values ('Cheese - Manchego, Spanish', 2366);
insert into Products (name, stock) values ('Lemonade - Black Cherry, 591 Ml', 6874);
insert into Products (name, stock) values ('Cucumber - English', 4660);
insert into Products (name, stock) values ('Coriander - Ground', 4301);
insert into Products (name, stock) values ('Cheese - Grana Padano', 1678);
insert into Products (name, stock) values ('Pepper - White, Ground', 5834);
insert into Products (name, stock) values ('Oxtail - Cut', 5767);
insert into Products (name, stock) values ('Beer - Blue', 8865);
insert into Products (name, stock) values ('Onions - White', 5355);
insert into Products (name, stock) values ('Pastry - Banana Tea Loaf', 5275);
insert into Products (name, stock) values ('Tea - Camomele', 5647);
insert into Products (name, stock) values ('Tart Shells - Sweet, 4', 2959);
insert into Products (name, stock) values ('Cake - Miini Cheesecake Cherry', 3856);
insert into Products (name, stock) values ('Soup - Tomato Mush. Florentine', 5680);
insert into Products (name, stock) values ('Soup Campbells - Italian Wedding', 3823);
insert into Products (name, stock) values ('Yukon Jack', 6293);
insert into Products (name, stock) values ('Mushroom - Porcini Frozen', 709);
insert into Products (name, stock) values ('Pasta - Fettuccine, Dry', 7929);
insert into Products (name, stock) values ('Seedlings - Buckwheat, Organic', 3429);
insert into Products (name, stock) values ('Ginger - Ground', 3771);
insert into Products (name, stock) values ('Nescafe - Frothy French Vanilla', 6491);
insert into Products (name, stock) values ('Halibut - Fletches', 2182);
insert into Products (name, stock) values ('Chicken - Wieners', 8578);
insert into Products (name, stock) values ('Assorted Desserts', 2063);
insert into Products (name, stock) values ('Lid Tray - 12in Dome', 2599);
insert into Products (name, stock) values ('Cheese - Cambozola', 556);
insert into Products (name, stock) values ('Wine - Lou Black Shiraz', 8480);
insert into Products (name, stock) values ('Vodka - Hot, Lnferno', 4118);
insert into Products (name, stock) values ('Chocolate Bar - Oh Henry', 2826);
insert into Products (name, stock) values ('Yeast Dry - Fermipan', 2345);
insert into Products (name, stock) values ('Molasses - Fancy', 7648);
insert into Products (name, stock) values ('Cleaner - Bleach', 3515);
insert into Products (name, stock) values ('Scallops - 10/20', 2994);
insert into Products (name, stock) values ('Scallop - St. Jaques', 4763);
insert into Products (name, stock) values ('Wine - Domaine Boyar Royal', 8442);
insert into Products (name, stock) values ('Pears - Bosc', 7021);

insert into Customers (name, vip) values ('Humfried McGerr', 1);
insert into Customers (name, vip) values ('Hamlin Hagard', 1);
insert into Customers (name, vip) values ('Ladonna Navarre', 0);
insert into Customers (name, vip) values ('Mirilla Maund', 1);
insert into Customers (name, vip) values ('Adolph Jime', 1);
insert into Customers (name, vip) values ('Giulia Buxey', 0);
insert into Customers (name, vip) values ('Gwenora Anthoine', 0);
insert into Customers (name, vip) values ('Babara Menico', 1);
insert into Customers (name, vip) values ('Ellsworth Litterick', 1);
insert into Customers (name, vip) values ('Wanda Eilert', 1);
insert into Customers (name, vip) values ('Trudie O''Keefe', 1);
insert into Customers (name, vip) values ('Nerti Marians', 1);
insert into Customers (name, vip) values ('Cobb Rubury', 0);
insert into Customers (name, vip) values ('Miltie Wellesley', 0);
insert into Customers (name, vip) values ('Alfonse Marking', 1);
insert into Customers (name, vip) values ('Sybila Bouette', 1);
insert into Customers (name, vip) values ('Marcus Borris', 1);
insert into Customers (name, vip) values ('Virginia Lampel', 0);
insert into Customers (name, vip) values ('Hilda Monson', 1);
insert into Customers (name, vip) values ('Ardella Offill', 0);
insert into Customers (name, vip) values ('Claire Coyish', 0);
insert into Customers (name, vip) values ('Shoshanna Durram', 0);
insert into Customers (name, vip) values ('Jenilee Tilbey', 1);
insert into Customers (name, vip) values ('Lebbie Brikner', 0);
insert into Customers (name, vip) values ('Erica Balf', 1);
insert into Customers (name, vip) values ('Zacharia Carrol', 0);
insert into Customers (name, vip) values ('Elsa Garrettson', 0);
insert into Customers (name, vip) values ('Gilli Renzullo', 1);
insert into Customers (name, vip) values ('Halsy Chanders', 0);
insert into Customers (name, vip) values ('Nehemiah Jaulme', 1);
insert into Customers (name, vip) values ('Hodge Janicijevic', 1);
insert into Customers (name, vip) values ('Mathilde Chadbourne', 0);
insert into Customers (name, vip) values ('Ezequiel Stobbie', 0);
insert into Customers (name, vip) values ('Lyon Weich', 1);
insert into Customers (name, vip) values ('Suzi Ovise', 1);
insert into Customers (name, vip) values ('Korie Dowall', 0);
insert into Customers (name, vip) values ('Rossy Beere', 0);
insert into Customers (name, vip) values ('Tomkin Jenteau', 0);
insert into Customers (name, vip) values ('Carmencita Talloe', 1);
insert into Customers (name, vip) values ('Arnuad Summerly', 0);
insert into Customers (name, vip) values ('Allsun Tidcombe', 1);
insert into Customers (name, vip) values ('Deana Pithie', 1);
insert into Customers (name, vip) values ('Jorgan Dunridge', 1);
insert into Customers (name, vip) values ('Rosabelle Palfrie', 0);
insert into Customers (name, vip) values ('Peg Gronaller', 1);
insert into Customers (name, vip) values ('Perle Peaddie', 1);
insert into Customers (name, vip) values ('Petronilla Labrone', 0);
insert into Customers (name, vip) values ('Pamelina Gauntley', 0);
insert into Customers (name, vip) values ('Agathe Sheehan', 0);
insert into Customers (name, vip) values ('Bax Garmon', 1);
insert into Customers (name, vip) values ('Roanna Grievson', 1);
insert into Customers (name, vip) values ('Alphard Giorgielli', 0);
insert into Customers (name, vip) values ('Pooh Worboy', 1);
insert into Customers (name, vip) values ('Alyssa Kiehnlt', 1);
insert into Customers (name, vip) values ('Stu Orrill', 1);
insert into Customers (name, vip) values ('Valery Brookwood', 0);
insert into Customers (name, vip) values ('Loraine Dwyer', 0);
insert into Customers (name, vip) values ('Nobe Glewe', 1);
insert into Customers (name, vip) values ('Zelma Bilton', 1);
insert into Customers (name, vip) values ('Winnifred Bourhill', 1);
insert into Customers (name, vip) values ('Marlene Marushak', 1);
insert into Customers (name, vip) values ('Karilynn Tripney', 0);
insert into Customers (name, vip) values ('Albertine Valois', 1);
insert into Customers (name, vip) values ('Dale Farreil', 0);
insert into Customers (name, vip) values ('Rowney Menchenton', 1);
insert into Customers (name, vip) values ('Viviene Swinbourne', 1);
insert into Customers (name, vip) values ('Broddie Menhci', 1);
insert into Customers (name, vip) values ('Gwennie Mounfield', 1);
insert into Customers (name, vip) values ('Alford Dexter', 1);
insert into Customers (name, vip) values ('Mel Young', 0);
insert into Customers (name, vip) values ('Dorrie Beinisch', 0);
insert into Customers (name, vip) values ('Windham Jovic', 1);
insert into Customers (name, vip) values ('Chiquita Huyhton', 1);
insert into Customers (name, vip) values ('Josh Lethbrig', 1);
insert into Customers (name, vip) values ('Kenon Seiter', 0);
insert into Customers (name, vip) values ('Rachele Novacek', 0);
insert into Customers (name, vip) values ('Anne-marie Norquoy', 1);
insert into Customers (name, vip) values ('Lynett Tandey', 0);
insert into Customers (name, vip) values ('Lavinie Glazer', 0);
insert into Customers (name, vip) values ('Margette Bodechon', 0);
insert into Customers (name, vip) values ('Bennie Kniveton', 1);
insert into Customers (name, vip) values ('Erma Baudon', 1);
insert into Customers (name, vip) values ('Basia Hounsome', 1);
insert into Customers (name, vip) values ('Virgie Preto', 0);
insert into Customers (name, vip) values ('Goran Vannar', 0);
insert into Customers (name, vip) values ('Jefferson Klimt', 0);
insert into Customers (name, vip) values ('Lorelei Yewdale', 1);
insert into Customers (name, vip) values ('Brit Wabersich', 1);
insert into Customers (name, vip) values ('Bendite Balnaves', 1);
insert into Customers (name, vip) values ('Sisile Jaycox', 0);
insert into Customers (name, vip) values ('Kendell Mabon', 1);
insert into Customers (name, vip) values ('Kermie Morshead', 1);
insert into Customers (name, vip) values ('Nicola Feben', 0);
insert into Customers (name, vip) values ('Avivah Hatry', 0);
insert into Customers (name, vip) values ('Davida Gumn', 0);
insert into Customers (name, vip) values ('Virgina Greenley', 1);
insert into Customers (name, vip) values ('Adelheid Tourne', 1);
insert into Customers (name, vip) values ('Herve Wroe', 0);
insert into Customers (name, vip) values ('Karly Tortis', 0);
insert into Customers (name, vip) values ('Cyrille Boar', 0);


insert into OrderDetails (customer_id, product_id, quantity) values (35, 158, 810);
insert into OrderDetails (customer_id, product_id, quantity) values (67, 159, 730);
insert into OrderDetails (customer_id, product_id, quantity) values (26, 197, 1445);
insert into OrderDetails (customer_id, product_id, quantity) values (85, 49, 1332);
insert into OrderDetails (customer_id, product_id, quantity) values (38, 158, 1483);
insert into OrderDetails (customer_id, product_id, quantity) values (23, 135, 628);
insert into OrderDetails (customer_id, product_id, quantity) values (18, 22, 705);
insert into OrderDetails (customer_id, product_id, quantity) values (69, 129, 1071);
insert into OrderDetails (customer_id, product_id, quantity) values (59, 187, 366);
insert into OrderDetails (customer_id, product_id, quantity) values (30, 163, 368);
insert into OrderDetails (customer_id, product_id, quantity) values (4, 135, 467);
insert into OrderDetails (customer_id, product_id, quantity) values (60, 113, 833);
insert into OrderDetails (customer_id, product_id, quantity) values (31, 108, 1790);
insert into OrderDetails (customer_id, product_id, quantity) values (16, 22, 811);
insert into OrderDetails (customer_id, product_id, quantity) values (59, 164, 1778);
insert into OrderDetails (customer_id, product_id, quantity) values (87, 182, 1054);
insert into OrderDetails (customer_id, product_id, quantity) values (40, 149, 403);
insert into OrderDetails (customer_id, product_id, quantity) values (91, 166, 1984);
insert into OrderDetails (customer_id, product_id, quantity) values (42, 52, 353);
insert into OrderDetails (customer_id, product_id, quantity) values (31, 12, 328);
insert into OrderDetails (customer_id, product_id, quantity) values (8, 66, 675);
insert into OrderDetails (customer_id, product_id, quantity) values (11, 122, 778);
insert into OrderDetails (customer_id, product_id, quantity) values (62, 118, 1238);
insert into OrderDetails (customer_id, product_id, quantity) values (64, 178, 1496);
insert into OrderDetails (customer_id, product_id, quantity) values (85, 1, 602);
insert into OrderDetails (customer_id, product_id, quantity) values (41, 165, 153);
insert into OrderDetails (customer_id, product_id, quantity) values (77, 192, 512);
insert into OrderDetails (customer_id, product_id, quantity) values (50, 157, 1555);
insert into OrderDetails (customer_id, product_id, quantity) values (26, 128, 1875);
insert into OrderDetails (customer_id, product_id, quantity) values (81, 158, 344);
insert into OrderDetails (customer_id, product_id, quantity) values (73, 116, 281);
insert into OrderDetails (customer_id, product_id, quantity) values (98, 92, 990);
insert into OrderDetails (customer_id, product_id, quantity) values (36, 61, 1763);
insert into OrderDetails (customer_id, product_id, quantity) values (68, 120, 57);
insert into OrderDetails (customer_id, product_id, quantity) values (93, 68, 994);
insert into OrderDetails (customer_id, product_id, quantity) values (4, 171, 579);
insert into OrderDetails (customer_id, product_id, quantity) values (84, 185, 126);
insert into OrderDetails (customer_id, product_id, quantity) values (69, 126, 1021);
insert into OrderDetails (customer_id, product_id, quantity) values (94, 86, 58);
insert into OrderDetails (customer_id, product_id, quantity) values (73, 34, 109);
insert into OrderDetails (customer_id, product_id, quantity) values (87, 33, 1947);
insert into OrderDetails (customer_id, product_id, quantity) values (49, 120, 810);
insert into OrderDetails (customer_id, product_id, quantity) values (78, 24, 902);
insert into OrderDetails (customer_id, product_id, quantity) values (97, 130, 1665);
insert into OrderDetails (customer_id, product_id, quantity) values (31, 86, 159);
insert into OrderDetails (customer_id, product_id, quantity) values (46, 127, 1223);
insert into OrderDetails (customer_id, product_id, quantity) values (6, 138, 1334);
insert into OrderDetails (customer_id, product_id, quantity) values (40, 7, 867);
insert into OrderDetails (customer_id, product_id, quantity) values (22, 30, 472);
insert into OrderDetails (customer_id, product_id, quantity) values (27, 133, 1045);
insert into OrderDetails (customer_id, product_id, quantity) values (50, 151, 1659);
insert into OrderDetails (customer_id, product_id, quantity) values (79, 30, 1198);
insert into OrderDetails (customer_id, product_id, quantity) values (55, 143, 802);
insert into OrderDetails (customer_id, product_id, quantity) values (7, 84, 1588);
insert into OrderDetails (customer_id, product_id, quantity) values (66, 132, 1606);
insert into OrderDetails (customer_id, product_id, quantity) values (63, 96, 1254);
insert into OrderDetails (customer_id, product_id, quantity) values (4, 84, 108);
insert into OrderDetails (customer_id, product_id, quantity) values (7, 187, 546);
insert into OrderDetails (customer_id, product_id, quantity) values (65, 11, 1590);
insert into OrderDetails (customer_id, product_id, quantity) values (96, 116, 1020);
insert into OrderDetails (customer_id, product_id, quantity) values (26, 200, 1485);
insert into OrderDetails (customer_id, product_id, quantity) values (74, 84, 1807);
insert into OrderDetails (customer_id, product_id, quantity) values (46, 127, 1862);
insert into OrderDetails (customer_id, product_id, quantity) values (47, 134, 255);
insert into OrderDetails (customer_id, product_id, quantity) values (72, 148, 1781);
insert into OrderDetails (customer_id, product_id, quantity) values (97, 7, 1296);
insert into OrderDetails (customer_id, product_id, quantity) values (71, 171, 615);
insert into OrderDetails (customer_id, product_id, quantity) values (58, 35, 1689);
insert into OrderDetails (customer_id, product_id, quantity) values (100, 36, 919);
insert into OrderDetails (customer_id, product_id, quantity) values (27, 73, 232);
insert into OrderDetails (customer_id, product_id, quantity) values (32, 157, 13);
insert into OrderDetails (customer_id, product_id, quantity) values (65, 57, 1285);
insert into OrderDetails (customer_id, product_id, quantity) values (50, 99, 700);
insert into OrderDetails (customer_id, product_id, quantity) values (52, 64, 1717);
insert into OrderDetails (customer_id, product_id, quantity) values (88, 152, 224);
